exports.array = {
    executive : [
        {
            model: "Executive Carry",
            number: "#96661",
            msrp: "1,399.00",
            caliber: ".45 ACP",
            specs: [
                '• 3" Ramped Stainless Steel Bull Barrel',
                '• Trijicon® Night Sights',
                '• Lightweight Aluminum Frame',
                '• Ed Brown® Bobtail™ Mainspring Housing',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond©/Anodized Finish',
                '• VZ© Machined G10 Grips',
                '• Two 8-Round magazines',
            ],
            desc: 'Simply the baddest concealed carry 1911 on the planet, hand built by our team of skilled artisans to keep you safe. Packs 8+1 rounds of .45 AUTO firepower in a lightweight, low-print design. Features an aluminum-alloy body, 3" barrel, and Ed Brown® Bobtail™ mainspring housing for max comfort and concealment.',
            image: 'images/gunImages/ExecutiveCarry.png',
            image_source: 'www.para-usa.com',
        }
    ],
    LDA :
    [
        {
            model: "LDA Officer .45",
            number: "#96641",
            msrp: "1,025.00",
            caliber: ".45 ACP",
            specs: [
                '• 3.5" Stainless Steel Match-Grade Ramped Barrel',
                '• 2-Dot Rear, Fiber Optic Front Sight',
                '• Stainless Frame & Slide',
                '• Beavertail Grip Safety',
                '• Full Length 1-Piece Guide Rod',
                '• Oversized, Flared Ejection Port',
                '• Ionbond© Finish',
                '• VZ© Machined G10 Grips',
                '• Two 7-Round Magazines',
            ],
            desc: 'For double action converts who prefer not to carry a "cocked and locked” 1911, PARA\'s LDA (Light Double Action) system delivers 1911 performance from a double action fire control. Fire it and you’ll never pickup a standard double action pistol again.',
            image: 'images/gunImages/LDAOfficer45.png',
            image_source: 'www.para-usa.com',
        },
        {
           model: "LDA Officer 9MM",
            number: "#96642",
            msrp: "1,025.00",
            caliber: "9MM",
            specs: [
                '• 3.5" Stainless Steel Match-Grade Ramped Barrel',
                '• 2-Dot Rear, Fiber Optic Front Sight',
                '• Stainless Frame & Slide',
                '• Beavertail Grip Safety',
                '• Full Length 1-Piece Guide Rod',
                '• Oversized, Flared Ejection Port',
                '• Ionbond© Finish',
                '• VZ© Machined G10 Grips',
                '• Two 9-Round Magazines',
            ],
            desc: 'For double action converts who prefer not to carry a “cocked and locked” 1911, PARA’s LDA (Light Double Action) system delivers 1911 performance from a double action fire control. Fire it and you’ll never pickup a standard double action pistol again.',
            image: 'images/gunImages/LDAOfficer9.png',
            image_source: 'www.para-usa.com', 
        },
        {
        model: "LDA Officer Crimson Trace \n.45",
            number: "#96650",
            msrp: "1,225.00",
            caliber: ".45 ACP",
            specs: [
                '• 3.5" Stainless Steel Match-Grade Ramped Barrel',
                '• Night Sights',
                '• Stainless Frame & Slide',
                '• Beavertail Grip Safety',
                '• LDA Fire Control',
                '• EGW® HD Extractor',
                '• Full Length 1-Piece Guide Rod',
                '• Oversized, Flared Ejection Port',
                '• Ionbond© PVD Slide & Frame',
                '• Crimson Trace® Laser Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'For double action converts who prefer not to carry a “cocked and locked” 1911, PARA’s LDA (Light Double Action) system delivers 1911 performance from a double action fire control. Fire it and you’ll never pickup a standard double action pistol again.',
            image: 'images/gunImages/LDAOCT45.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "LDA Officer Crimson Trace 9MM",
            number: "#96651",
            msrp: "1,225.00",
            caliber: "9MM",
            specs: [
                '• 3.5" Stainless Steel Match-Grade Ramped Barrel',
                '• Night Sights',
                '• Stainless Frame & Slide',
                '• Beavertail Grip Safety',
                '• LDA Fire Control',
                '• EGW® HD Extractor',
                '• Full Length 1-Piece Guide Rod',
                '• Oversized, Flared Ejection Port',
                '• Ionbond© PVD Slide & Frame',
                '• Crimson Trace® Laser Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'For double action converts who prefer not to carry a “cocked and locked” 1911, PARA’s LDA (Light Double Action) system delivers 1911 performance from a double action fire control. Fire it and you’ll never pickup a standard double action pistol again.',
            image: 'images/gunImages/LDAOCT9.png',
            image_source: 'www.para-usa.com',
        },
        {
          model: "LDA Carry .45",
            number: "#96643",
            msrp: "1,025.00",
            caliber: ".45 ACP",
            specs: [
                '• 3" Stainless Steel Match-Grade Ramped Barrel',
                '• 2-Dot Rear, Fiber Optic Front Sight',
                '• Stainless Frame & Slide',
                '• Beavertail Grip Safety',
                '• Full Length 1-Piece Guide Rod',
                '• Oversized, Flared Ejection Port',
                '• Ionbond© Finish',
                '• VZ© Machined G10 Grips',
                '• Two 6-Round Magazines',
            ],
            desc: 'For double action converts who prefer not to carry a “cocked and locked” 1911, PARA’s LDA (Light Double Action) system delivers 1911 performance from a double action fire control. Fire it and you’ll never pickup a standard double action pistol again.',
            image: 'images/gunImages/LDAC45.png',
            image_source: 'www.para-usa.com',  
        },
        {
            model: "LDA Carry 9MM",
            number: "#96645",
            msrp: "1,025.00",
            caliber: ".9MM",
            specs: [
                '• 3" Stainless Steel Match-Grade Ramped Barrel',
                '• 2-Dot Rear, Fiber Optic Front Sight',
                '• Stainless Frame & Slide',
                '• Beavertail Grip Safety',
                '• Full Length 1-Piece Guide Rod',
                '• Oversized, Flared Ejection Port',
                '• Ionbond© Finish',
                '• Cocobolo Checkered Double Diamond Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'For double action converts who prefer not to carry a “cocked and locked” 1911, PARA’s LDA (Light Double Action) system delivers 1911 performance from a double action fire control. Fire it and you’ll never pickup a standard double action pistol again.',
            image: 'images/gunImages/LDAC9.png',
            image_source: 'www.para-usa.com',
        },
        
    ],
    Competition :
    [
        {
            model: "Tomasie Custom",
            number: "#96724",
            msrp: "1,999.00",
            caliber: ".40 S&W",
            specs: [
                '• Designed by Travis Tomasie',
                '• 5" Stainless Match-Grade Ramped Bull Barrel',
                '• Adjustable Target Rear, Fiber Optic Front Sight',
                '• EGW® Fire Control and HD Extractor',
                '• Full Length Guide Rod',
                '• Stainless Steel Slide with Tri-Top & Lightening Cuts',
                '• PARA Oversized Magwell',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 16-Round Double Stack Magazines',
            ],
            desc: 'Designed in conjunction with IPSC World Champion Travis Tomasie, this lineup combines uncompromising fit and finish with features today’s top competitors demand. The foundation being superb handling, tack-driving accuracy and the precision-fit our elite corps of craftsmen bring to the table and across the finish line with honors.',
            image: 'images/gunImages/TomasieCustom.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Pro Comp .40",
            number: "#96711",
            msrp: "1,299.00",
            caliber: ".40 S&W",
            specs: [
                '• 5" Stainless Match-Grade Ramped Barrel',
                '• Adjustable Target Rear, Fiber Optic Front Sight',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Full Length Guide Rod',
                '• Beavertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 8-Round Standard Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/ProComp40.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Pro Comp 9MM",
            number: "#96790",
            msrp: "1,299.00",
            caliber: "9MM",
            specs: [
                '• 5" Stainless Match-Grade Ramped Barrel',
                '• Adjustable Target Rear, Fiber Optic Front Sight',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Full Length Guide Rod',
                '• Beavertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                'VZ® Operator™ Machined G10 Grips',
                '• Two Standard Capacity Magazines',
            ],
            desc: 'Give your competition a handcrafted lesson in humility straight out of Pineville, NC. Designed in conjunction with IPSC World Champion Travis Tomasie, this lineup combines uncompromising ft and fnish with features today’s top competitors demand. The foundation being superb handling, tack-driving accuracy and the precision-ft our elite corps of craftsmen bring to the table and across the fnish line with honors.',
            image: 'images/gunImages/ProComp9.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Pro Custom 14.45",
            number: "#96705",
            msrp: "1,449.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Stainless Match-Grade Ramped Barrel',
                '• Adjustable Target Rear, Fiber Optic Front Sight',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Full Length Guide Rod',
                '• Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 14 Round Double Stack Magazines',
            ],
            desc: 'Give your competition a handcrafted lesson in humility straight out of Pineville, NC. Designed in conjunction with IPSC World Champion Travis Tomasie, this lineup combines uncompromising ft and fnish with features today’s top competitors demand. The foundation being superb handling, tack-driving accuracy and the precision-ft our elite corps of craftsmen bring to the table and across the fnish line with honors.',
            image: 'images/gunImages/Pro1445.png',
            image_source: 'www.para-usa.com',  
        },
        {
            model: "Pro Custom 10.45",
            number: "#96706",
            msrp: "1,449.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Stainless Match-Grade Ramped Barrel',
                '• Adjustable Target Rear, Fiber Optic Front Sight',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Full Length Guide Rod',
                '• Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 10 Round Double Stack Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA. NOTE: magwel shown in image not included.',
            image: 'images/gunImages/Pro1045.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Pro Custom 16.40",
            number: "#96707",
            msrp: "1,449.00",
            caliber: ".40 S&W",
            specs: [
                '• 5" Stainless Match-Grade Ramped Barrel',
                '• Adjustable Target Rear, Fiber Optic Front Sight',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Full Length Guide Rod',
                '• Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 16 Round Double Stack Magazines',
            ],
            desc: 'Give your competition a handcrafted lesson in humility straight out of Pineville, NC. Designed in conjunction with IPSC World Champion Travis Tomasie, this lineup combines uncompromising fit and finish with features today’s top competitors demand. The foundation being superb handling, tack-driving accuracy and the precision-fit our elite corps of craftsmen bring to the table and across the finish line with honors.',
            image: 'images/gunImages/Pro1640.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Pro Custom 18.9",
            number: "#96709",
            msrp: "1,449.00",
            caliber: "9MM",
            specs: [
                '• 5" Stainless Match-Grade Ramped Barrel',
                '• Adjustable Target Rear, Fiber Optic Front Sight',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Full Length Guide Rod',
                '• Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 18 Round Double Stack Magazines',
            ],
            desc: 'Give your competition a handcrafted lesson in humility straight out of Pineville, NC. Designed in conjunction with IPSC World Champion Travis Tomasie, this lineup combines uncompromising fit and finish with features today’s top competitors demand. The foundation being superb handling, tack-driving accuracy and the precision-fit our elite corps of craftsmen bring to the table and across the finish line with honors.',
            image: 'images/gunImages/Pro189.png',
            image_source: 'www.para-usa.com',
        },
    ],
    Tactical :
    [
        {
            model: "1911 Black Ops",
            number: "#96690",
            msrp: "1,257.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Ramped Barrel',
                '• Trijicon® Tritium Night Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Integral Accessory Rail',
                '• Beaver Tail Grip & Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 8-Round Standard Magazines',
            ],
            desc: 'Developed by the most influential minds in pistol design, and packed with the highest capacity and most firepower found in a 1911 tactical pistol – up to 14 rounds of .45 AUTO. Add in the excellent handling, expert precision and an uncompromising group of features, and you’ve got the ultimate sidearm should your situation go from bad to brutal. From Pineville, NC. To hell and back..',
            image: 'images/gunImages/1911BO.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Black Ops 14.45",
            number: "#96694",
            msrp: "1,299.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Ramped Barrel',
                '• Trijicon® Tritium Night Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Checkerd Front Strap',
                '• Integral Accessory Rail',
                '• Beaver Tail Grip & Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 14-Round Double Stack Magazines',
            ],
            desc: 'Developed by the most influential minds in pistol design, and packed with the highest capacity and most firepower found in a 1911 tactical pistol – up to 14 rounds of .45 AUTO. Add in the excellent handling, expert precision and an uncompromising group of features, and you’ve got the ultimate sidearm should your situation go from bad to brutal. From Pineville, NC. To hell and back..',
            image: 'images/gunImages/BO1445.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Black Ops 10.45",
            number: "#96696",
            msrp: "1,299.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Ramped Barrel',
                '• Trijicon® Tritium Night Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Checkerd Front Strap',
                '• Integral Accessory Rail',
                '• Beaver Tail Grip & Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 10-Round Double Stack Magazines',
            ],
            desc: 'Developed by the most influential minds in pistol design, and packed with the highest capacity and most firepower found in a 1911 tactical pistol – up to 14 rounds of .45 AUTO. Add in the excellent handling, expert precision and an uncompromising group of features, and you’ve got the ultimate sidearm should your situation go from bad to brutal. From Pineville, NC. To hell and back..',
            image: 'images/gunImages/BO1045.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Black Ops Combat",
            number: "#96698",
            msrp: "1,325.00",
            caliber: ".45 ACP",
            specs: [
                '• 5.5" Stainless Steel Barrel',
                '• Threaded Ramped Barrel',
                '• High-Profile Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Checkerd Front Strap',
                '• Integral Accessory Rail',
                '• Beaver Tail Grip & Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 14-Round Double Stack Magazines',
            ],
            desc: 'Developed by the most influential minds in pistol design, and packed with the highest capacity and most firepower found in a 1911 tactical pistol – up to 14 rounds of .45 AUTO. Add in the excellent handling, expert precision and an uncompromising group of features, and you’ve got the ultimate sidearm should your situation go from bad to brutal. From Pineville, NC. To hell and back..',
            image: 'images/gunImages/BOCombat.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Black Ops Recon",
            number: "#96697",
            msrp: "1,299.00",
            caliber: ".45 ACP",
            specs: [
                '• 4.25" Ramped Barrel',
                '• Trijicon® Tritium Night Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Checkerd Front Strap',
                '• Integral Accessory Rail',
                '• Beaver Tail Grip & Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 14-Round Double Stack Magazines',
            ],
            desc: 'Developed by the most influential minds in pistol design, and packed with the highest capacity and most firepower found in a 1911 tactical pistol – up to 14 rounds of .45 AUTO. Add in the excellent handling, expert precision and an uncompromising group of features, and you’ve got the ultimate sidearm should your situation go from bad to brutal. From Pineville, NC. To hell and back..',
            image: 'images/gunImages/BORecon.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Black Ops Recon 9MM",
            number: "#96699",
            msrp: "1,299.00",
            caliber: "9MM",
            specs: [
                '• 4.25" Ramped Barrel',
                '• Trijicon® Tritium Night Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Checkerd Front Strap',
                '• Integral Accessory Rail',
                '• Beaver Tail Grip & Ambidextrous Thumb Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 18-Round Double Stack Magazines',
            ],
            desc: 'Developed by the most influential minds in pistol design, and packed with the highest capacity and most firepower found in a 1911 tactical pistol – up to 14 rounds of .45 AUTO. Add in the excellent handling, expert precision and an uncompromising group of features, and you’ve got the ultimate sidearm should your situation go from bad to brutal. From Pineville, NC. To hell and back..',
            image: 'images/gunImages/BORecon9.png',
            image_source: 'www.para-usa.com',
        },
    ],
    Elite :
    [
        {
            model: "Elite",
            number: "#96663",
            msrp: "949.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Ramped Barrel',
                '• 2-Dot Rear, Green Fiber Optic Front',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Beaver Tail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• Cocobolo Double Diamond Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/Elite.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite Stainless",
            number: "#96671",
            msrp: "999.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Ramped Barrel',
                '• 2-Dot Rear, Green Fiber Optic Front',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Beaver Tail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Satin Stainless Steel Finish',
                '• Cocobolo Double Diamond Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/EliteStainless.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite Target",
            number: "#96664",
            msrp: "999.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Ramped Barrel',
                '• Adjustable Rear Target Sight, Green Fiber Optic Front',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Beaver Tail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Satin Stainless Steel Finish',
                '• Ionbond® PVD Frame',
                '• Cocobolo Double Diamond Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/EliteTarget.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite Pro",
            number: "#96665",
            msrp: "1,249.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Ramped Barrel',
                '• Trijicon® Night Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Beaver Tail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond® PVD Frame',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/ElitePro.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite Pro Stainless",
            number: "#96672",
            msrp: "1,299.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Ramped Barrel',
                '• Trijicon® Night Sights',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Ed Brown® Magwell',
                '• Skeletonized Match Grade Trigger',
                '• Satin Stainless Steel Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/EliteProStainless.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite LS Hunter",
            number: "#96666",
            msrp: "1,249.00",
            caliber: "10MM",
            specs: [
                '• 6" Match-Grade Ramped Barrel',
                '• Adjustable Rear Target Sight, Green Fiber Optic Front',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• VZ® Operator™ Machined G10 Grips',
                '• Two 9-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/EliteLS.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite Commander",
            number: "#96667",
            msrp: "949.00",
            caliber: ".45 ACP",
            specs: [
                '• 4.25" Stainless Match-Grade Ramped Barrel',
                '• 2-Dot Rear, Green Fiber Optic Front',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• Cocobolo Double Diamond Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/EliteCommander.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite Officer",
            number: "#96668",
            msrp: "949.00",
            caliber: ".45 ACP",
            specs: [
                '• 3.5" Stainless Match-Grade Ramped Barrel',
                '• 2-Dot Dovetail Rear, Green Fiber Optic Front',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond© PVD Finish',
                '• Cocobolo Double Diamond Grips',
                '• Two 7-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/EliteOfficer.png',
            image_source: 'www.para-usa.com',
        },
        {
            model: "Elite Carry",
            number: "#96669",
            msrp: "949.00",
            caliber: ".45 ACP",
            specs: [
                '• 3" Stainless Match-Grade Ramped Barrel',
                '• 2-Dot Dovetail Rear, Green Fiber Optic Front',
                '• Stainless Steel Frame & Slide',
                '• EGW® HD Extractor',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Ionbond©/Anodize Finish',
                '• Cocobolo Double Diamond Grips',
                '• Two 6-Round Magazines',
            ],
            desc: 'Out of the box and in your hands, never has the icon performed better. Starting with only the finest precision-engineered parts, each pistol is hand-assembled and fine-tuned for perfection by the most demanding, dedicated craftsmen in the industry. The result is a true classic without compromise, featuring the customgrade quality and timeless looks of a high-end 1911, plus a host of innovations first developed, and still done best, by PARA.',
            image: 'images/gunImages/EliteCarry.png',
            image_source: 'www.para-usa.com',
        },
    ],
    Expert:
    [
    	{	
    		model: "Expert",
            number: "#96746",
            msrp: "663.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Stainless Slide & Steel Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride Finish',
                '• Polymer Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/Expert.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert 9MM",
            number: "#96749",
            msrp: "663.00",
            caliber: "9MM",
            specs: [
                '• 5" Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Stainless Slide & Steel Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride Finish',
                '• Polymer Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/Expert9.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert Stainless",
            number: "#96746",
            msrp: "713.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Stainless Slide & Steel Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Stainless Finish',
                '• Polymer Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/ExpertStainless.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert Commander",
            number: "#96748",
            msrp: "799.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Stainless Steel Slide & Aluminum Frame',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride/Anodize Finish',
                '• Polymer Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/ExpertCommander.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert Carry",
            number: "#96745",
            msrp: "6799.00",
            caliber: ".45 ACP",
            specs: [
                '• 3" Match-Grade Barrel',
                '• 2-Dot Rear, Green Fiber Optic Front',
                '• Stainless Steel Slide & Aluminum Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride/Anodize Finish',
                '• Polymer Grips',
                '• Two 8-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/ExpertCarry.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert 14.45",
            number: "#96765",
            msrp: "884.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Double-Stack Stainless Steel Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride Finish',
                '• Polymer Grips',
                '• Two 14-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/Expert1445.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert 10.45",
            number: "#96767",
            msrp: "884.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Double-Stack Stainless Steel Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride Finish',
                '• Polymer Grips',
                '• Two 10-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/Expert1045.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert 14.45 Stainless",
            number: "#96766",
            msrp: "919.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Stainless Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Double-Stack Stainless Steel Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Stainless Finish',
                '• Polymer Grips',
                '• Two 14-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/Expert1445Stainless.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Expert 10.45 Stainless",
            number: "#96768",
            msrp: "919.00",
            caliber: ".45 ACP",
            specs: [
                '• 5" Stainless Match-Grade Barrel',
                '• Green Fiber Optic Front',
                '• Double-Stack Stainless Steel Frame',
                '• Oversized, Flared Ejection Port',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Stainless Finish',
                '• Polymer Grips',
                '• Two 10-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/Expert1045Stainless.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Warthog",
            number: "#96600",
            msrp: "884.00",
            caliber: ".45 ACP",
            specs: [
                '• 3" Stainless Match-Grade Barrel',
                '• 2-Dot Rear, Green Fiber Optic Front',
                '• Stainless Steel Slide & Aluminum Frame',
                '• EGW® HD Extractor ',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride/Anodize Finish',
                '• Polymer Grips',
                '• Two Double-Stack 10-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/Warthog.png',
            image_source: 'www.para-usa.com',
    	},
    	{	
    		model: "Warthog Stainless",
            number: "#96602",
            msrp: "919.00",
            caliber: ".45 ACP",
            specs: [
                '• 3" Stainless Match-Grade Barrel',
                '• 2-Dot Rear, Green Fiber Optic Front',
                '• Stainless Steel Slide & Frame',
                '• EGW® HD Extractor ',
                '• Bevertail Grip Safety',
                '• Skeletonized Match Grade Trigger',
                '• Black Nitride/Anodize Finish',
                '• Polymer Grips',
                '• Two Double-Stack 10-Round Magazines',
            ],
            desc: 'Everyone should be able to own a PARA 1911. Case closed. With that in mind, we offer up our Expert Series. True to the PARA way, all are hand tuned on a bench and test fired. And each features match-grade barrels, crisp triggers and loads of firepower. They’re built to the highest standards of our craft, with a few less features to keep costs down.',
            image: 'images/gunImages/WarthogStainless.png',
            image_source: 'www.para-usa.com',
    	},
    ],
};